sudo: required
language: shell
group: bluezone

git:
  submodules: false
  depth: 10
services:
  - docker

os:
  - linux-ppc64le

env:
    matrix:
       - DISTRO='rhel81'
       - DISTRO='rhel8'
       - DISTRO='rhel76'
       - DISTRO='rhel77'
       - DISTRO='rhel78'
       - DISTRO='rhelalt76'

install:
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch --all
  - git branch -avv

script:
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then scp "glwalbon@hurgsa.ibm.com:/projects/b/btaas_images/${DISTRO}.tar.gz" . ; fi
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then zcat "${DISTRO}.tar.gz" | docker import - "${DISTRO}"; fi
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then docker run -v $(pwd):/root/kernels -w /root/kernels/ -it ${DISTRO} /root/kernels/.update -f "${FTP3_Credentials}" -d "${DISTRO}" -n "${My_Name}" -e "${My_Email}" ;fi


