sudo: required
language: shell
os: linux-ppc64le

git:
  submodules: false
  depth: 10
services:
  - docker
env:
    matrix:
       - DISTRO=rhel88
install:
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*

branches:
  only:
    - master

script:
  - sudo sed -i -- 's/#   StrictHostKeyChecking ask/StrictHostKeyChecking no/g' /etc/ssh/ssh_config
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then scp "glwalbon@hurgsa.ibm.com:/projects/b/btaas_images/${DISTRO}.tar.gz" . ; fi
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then zcat "${DISTRO}.tar.gz" | docker import - "${DISTRO}" && rm -rf "${DISTRO}.tar.gz"; fi
  - docker run -v $(pwd):/root/kernels -w /root/kernels/ -it ${DISTRO} /root/kernels/.update -f "${FTP3_Credentials}" -d "${DISTRO}" -n "${My_Name}" -e "${My_Email}"
